### ISSUE TITLE
can't read "password": no such variable

### ISSUE THREAD

**Issue by HorlogeSkynet** [Tulux/Wifirst_keepalive#3]
Salut !

J'ai donc cette erreur qui remonte juste après l'étape 3 "Validating".

![2015-04-14--1429032248_1088x322_scrot](https://cloud.githubusercontent.com/assets/5331869/7142892/00184408-e2dc-11e4-9632-0129a9f73c48.png)

À noter, il met la même erreur avec "username" quand le mot de passe est erroné...

**Comment by Tulux** [comment]
Salut,

Executes-tu bien le script dans un environnement wifirst ?

**Comment by HorlogeSkynet** [comment]
Oui effectivement, par contre le site "parent" est en http://smartcampus.wifirst.net/ et non en http://selfcare.wifirst.net/

Mais même l'URL changée dans le script, l'erreur demeure...

**Comment by Tulux** [comment]
Je ne suis pas en ce moment sur le réseau wifirst donc je ne peux faire aucun test, par contre est-ce que tu laisses bien le script après que tu te sois authentifié au moins une fois ?
Normalement le script est à utilier pour automatiser le processus de reconnexion qui se traduit par une page demandant les identifiants toutes les semaines.

Sinon il est aussi possible qu'ils aient changé l'interface.
Mais comme ça je ne peux pas te dire.

Je garde le bug ouvert. Si j'ai l'occasion de revenir sur le réseau Wifirst dans les semaines/mois qui viennent (je ne suis plus chez moi) je regarderai, sinon j'abandonnerai la maintenance.

**Comment by HorlogeSkynet** [comment]
Je simule une telle "deconnexion" à l'aide du bouton Déconnecter, mais le résultat est le même...
Connecté ou non sur la page Wifirst, pareil.

D'accord, je vois de mon côté si je peux faire tester par quelqu'un d'autre ;)

**Comment by HorlogeSkynet** [comment]
Trop vieux, je nettoie. Ciao 👋
